export const rootTheme = {
	colors: {
		primary: '#1A1A1A',
		primaryForeground: '#ffffff',
		success: '#0C9409',
		successForeground: '#ffffff',
		card: '#ffffff',
		destructive: '#ED1010',
		destructiveForeground: '#ffffff',
		warning: '#FFA928',
		warningForeground: '#ffffff',
		background: '#ffffff',
		foreground: '#1A1A1A',
		muted: '#CCCCCC',
		mutedForeground: '#808080',
		border: '#E6E6E6',
		input: '#ffffff',
	},
	fonts: {
		regular: 'Inter_400Regular',
		medium: 'Inter_500Medium',
		semiBold: 'Inter_600SemiBold',
	},
	fontSizes: {
		xxxl: 64,
		xxl: 32,
		xl: 24,
		lg: 20,
		base: 16,
		sm: 14,
		xs: 12,
	},
	spaces: {
		xl: 24,
		lg: 20,
		md: 16,
		sm: 12,
		xs: 8,
		xxs: 4,
	},
	rounded: {
		lg: 20,
		md: 10,
		sm: 6,
	},
};
